apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pf8wm3mtf-java-springboot
  janus-idp.io/tekton: pf8wm3mtf-java-springboot
  backstage.io/kubernetes-id: pf8wm3mtf-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: pf8wm3mtf-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
